# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
neoforge_version=21.11.10-beta
neoforge_version_range=[21.11.10-beta,)

# Mod Properties
mod_version=2.1.2+1.21.11
maven_group=de.dafuqs
archives_base_name=foodeffecttooltips