# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# check these on https://neoforged.net/
minecraft_version=26.1.0
minecraft_version_range=[26.1.0,)
neoforge_version=26.1.0.19-beta
neoforge_version_range=[26.1.0.19-beta,)

# Mod Properties
mod_version=2.1.2+26.1
maven_group=de.dafuqs
archives_base_name=foodeffecttooltips