# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Minecraft
minecraft_version=26.2.0
minecraft_version_range=[26.2.0,)
# https://projects.neoforged.net/neoforged/neogradle
neogradle_version=7.1.38
# https://neoforged.net/
neoforge_version=26.2.0.12-beta
neoforge_version_range=[26.2.0.12-beta,)

# Mod Properties
mod_group_id=de.dafuqs
mod_id=foodeffecttooltips
mod_version=2.1.2+26.2
mod_name=Food Effect Tooltips
archives_base_name=FoodEffectTooltips
mod_license=lGPL3
mod_authors=DaFuqs
mod_description=Adds tooltips to foods which grant status effects when eaten
issue_tracker_url=https://github.com/DaFuqs/FoodEffectTooltips/issues
display_url=https://github.com/DaFuqs/FoodEffectTooltips