license = "lGPL3"
issueTrackerURL = "https://github.com/DaFuqs/FoodEffectTooltips/issues"

[[mods]]
modId = "foodeffecttooltips"
version = "${version}"
displayName = "Food Effect Tooltips"
displayURL = "github.com/DaFuqs/FoodEffectTooltips"
logoFile = "assets/foodeffecttooltips/icon.png"
authors = "Dafuqs"
description = '''Adds tooltips to foods which grant status effects when eaten'''

[[dependencies.foodeffecttooltips]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.foodeffecttooltips]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"